"""
BaselineAGENTWorkflow - PocketFlow Workflow

Baseline generation snapshot for AGENT pattern

Generated by Agent OS + PocketFlow Generator
"""

from .flow import BaselineAGENTWorkflowFlow
from .nodes import 

__version__ = "0.1.0"
__all__ = [
    "BaselineAGENTWorkflowFlow",
    
]
