"""
TaskManager - PocketFlow Workflow

Simple CRUD application for managing tasks

Generated by Agent OS + PocketFlow Generator
"""

from .flow import TaskManagerFlow
from .nodes import ValidateTask, ProcessTask, FormatResponse

__version__ = "0.1.0"
__all__ = [
    "TaskManagerFlow",
    "ValidateTask", "ProcessTask", "FormatResponse"
]
