"""
BaselineRAGWorkflow - PocketFlow Workflow

Baseline generation snapshot for RAG pattern

Generated by Agent OS + PocketFlow Generator
"""

from .flow import BaselineRAGWorkflowFlow
from .nodes import 

__version__ = "0.1.0"
__all__ = [
    "BaselineRAGWorkflowFlow",
    
]
