[tool.uv]
dev-dependencies = [
    "factory-boy>=3.3.0",
    "httpx>=0.25.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.1.0",
    "pytest>=7.0.0",
    "ruff>=0.1.0",
    "ty>=0.5.0",
]

[tool.uv.sources]
# Add any local package sources here if needed

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
