"""
BaselineWORKFLOWWorkflow - PocketFlow Workflow

Baseline generation snapshot for WORKFLOW pattern

Generated by Agent OS + PocketFlow Generator
"""

from .flow import BaselineWORKFLOWWorkflowFlow
from .nodes import InputValidator, BusinessLogicProcessor, OutputFormatter

__version__ = "0.1.0"
__all__ = [
    "BaselineWORKFLOWWorkflowFlow",
    "InputValidator", "BusinessLogicProcessor", "OutputFormatter"
]
